experiment_name: "2d_function_optimization_ppo_per_cycle_low_budget"

backend:
  name: "OptimizationBenchmarkBackend"
  params:
    function_name: "rastrigin"  # Можно изменить на sphere, rosenbrock и т.д.
    dimensions: 2
    noise_std: 0
    maximize: False  # False = минимизация

environment:
  name: "CyclicPipelineEnv"
  params:
    num_bins: 300
    max_steps: 100  # Резко снижено для проверки поведения при малом бюджете
    reward_mode: "per_cycle"  # Reward только после полного цикла
    step_sizes: [25, 5, 1]  # Ограничено до 1, 5, и 25 для совместимости с другими конфигами
    use_history: true  # Feedforward агенту нужна история
    history_cycles: 3  # Сколько циклов хранить (× num_params = длина окна)
  hp_space:
    x0:
      continuous:
        type: float
        log: False
        range: [-5.12, 5.12]
    x1:
      continuous:
        type: float
        log: False
        range: [-5.12, 5.12]

agent:
  name: "PPO"
  policy: "MultiInputPolicy"
  params:
    verbose: 1
    # seed: 42
    gamma: 0.95
    learning_rate: 0.003

training:
  total_timesteps: 10000  # 100 эпизодов (100 шагов * 100 эпизодов)

save_path: "model_2d_ppo_per_cycle_low_budget"

