functions:
  rastrigin: 
    min: -5.12
    max: 5.12
  sphere: sphere
  rosenbrock: rosenbrock
  ackley: ackley
  griewank: griewank
  schwefel: schwefel
  levy: levy
  michalewicz: michalewicz
  nondiff: nondiff
  booth: booth
  beale: beale
  goldstein_price: goldstein_price
  shifted_sphere: shifted_sphere
  shifted_rastrigin: shifted_rastrigin