functions:
  rastrigin: 
    min: -5.12
    max: 5.12
  sphere: 
    min: -5.12
    max: 5.12
  rosenbrock: rosenbrock
  ackley: ackley
  griewank: griewank
  schwefel: schwefel
  levy: levy
  michalewicz: michalewicz
  nondiff: nondiff
  booth: booth
  beale: beale
  goldstein_price:
    min: -2.0
    max: 2.0
  shifted_sphere: shifted_sphere
  shifted_rastrigin: shifted_rastrigin