experiment_name: "2d_booth_optimization"
# Booth function: min at (1, 3) - НЕ в центре!

backend:
  name: "OptimizationBenchmarkBackend"
  params:
    function_name: "booth"
    dimensions: 2
    noise_std: 0
    maximize: False

environment:
  name: "CyclicPipelineEnv"
  params:
    num_bins: 300
    max_steps: 1000
    reward_mode: "per_step"
    step_sizes: [25, 5, 1]
  hp_space:
    x0:
      continuous:
        type: float
        log: False
        range: [-10.0, 10.0]
    x1:
      continuous:
        type: float
        log: False
        range: [-10.0, 10.0]

agent:
  name: "PPO"
  policy: "MultiInputPolicy"
  params:
    verbose: 1
    # seed: 42
    gamma: 0.95
    learning_rate: 0.0003

training:
  total_timesteps: 200000

save_path: "model_2d_booth"

