models:
  simple_cnn:
    name: simple_cnn
    n_params:
      type: int
      min: 1
      max: 512
    optimizer:
      type: categorical
      values: ["SGD", "Adam"]
    criterion:
      type: categorical
      values: ["CrossEntorpyLoss"]

