experiment_name: "2d_shifted_sphere_optimization"
# Shifted Sphere: min at (2, 2) - НЕ в центре!
# Простая выпуклая функция, но со сдвинутым минимумом

backend:
  name: "OptimizationBenchmarkBackend"
  params:
    function_name: "shifted_sphere"
    dimensions: 2
    noise_std: 0
    maximize: False

environment:
  name: "CyclicPipelineEnv"
  params:
    num_bins: 300
    max_steps: 1000
    reward_mode: "per_step"
    step_sizes: [25, 5, 1]
  hp_space:
    x0:
      continuous:
        type: float
        log: False
        range: [-5.0, 5.0]
    x1:
      continuous:
        type: float
        log: False
        range: [-5.0, 5.0]

agent:
  name: "PPO"
  policy: "MultiInputPolicy"
  params:
    verbose: 1
    # seed: 42
    gamma: 0.95
    learning_rate: 0.0003

training:
  total_timesteps: 200000

save_path: "model_2d_shifted_sphere"

