experiment_name: "2d_rosenbrock_optimization"

backend:
  name: "OptimizationBenchmarkBackend"
  params:
    function_name: "rosenbrock"  # Долина - сложная для оптимизации
    dimensions: 2
    noise_std: 0
    maximize: False  # False = минимизация

environment:
  name: "CyclicPipelineEnv"
  params:
    num_bins: 300  # Значительно увеличено для более точного поиска
    max_steps: 1000  # Больше шагов для исследования пространства
    reward_mode: "per_step"  # Reward после каждого шага
    step_sizes: [25, 5, 1]  # Ограничено до 1, 5, и 25
  hp_space:
    x0:
      continuous:
        type: float
        log: False
        range: [-2.0, 2.0]  # Rosenbrock обычно тестируют на [-2, 2]
    x1:
      continuous:
        type: float
        log: False
        range: [-2.0, 2.0]

agent:
  name: "PPO"
  policy: "MultiInputPolicy"
  params:
    verbose: 1
    # seed: 42
    gamma: 0.95
    learning_rate: 0.003
    device: "cpu"

training:
  total_timesteps: 200000  # Увеличено для лучшего обучения с большим пространством действий

save_path: "model_2d_rosenbrock"

